# Generated by Django 5.0.3 on 2024-03-22 05:20

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0002_alter_users_created_at_alter_users_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
                ('images', models.JSONField(default=dict, null=True)),
                ('content', models.TextField()),
                ('amenity', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, null=True, size=None)),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('like_avg_score', models.FloatField(default=0.0)),
                ('like_count', models.IntegerField(default=0)),
                ('clip_count', models.IntegerField(default=0)),
                ('available_start_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 13, 946301, tzinfo=datetime.timezone.utc))),
                ('available_end_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 13, 946301, tzinfo=datetime.timezone.utc))),
                ('position', models.CharField(default=None, max_length=64, null=True)),
                ('hashtag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=None, null=True, size=None)),
                ('public', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auths.users')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 13, 948300, tzinfo=datetime.timezone.utc))),
                ('public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auths.users')),
                ('post_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.posts')),
            ],
        ),
    ]
