# Generated by Django 5.0.3 on 2024-03-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 30, 805454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='available_end_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 30, 805454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='available_start_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 30, 805454, tzinfo=datetime.timezone.utc)),
        ),
    ]
