version: "3.8"

services:
  api:
    build: .
    container_name: yxsapi01
    image: yxsapi:latest
    networks:
      - myappnet
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - dbms
      - cachedb

  dbms:
    image: mariadb:11
    container_name: mariadb01
    networks:
      - myappnet
    ports:
      - 3306:3306
    env_file:
      - .env.dev
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always

  cachedb:
    image: redis:alpine3.18
    container_name: redis01
    networks:
      - myappnet
    ports:
      - 6379:6379
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - dbms

networks:
  myappnet:
