"""init

Revision ID: 0be4241746dd
Revises: 
Create Date: 2024-03-01 15:03:33.515526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0be4241746dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.VARCHAR(length=18), nullable=False),
    sa.Column('tag', sa.VARCHAR(length=30), nullable=False),
    sa.Column('note', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hashtags_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), nullable=False),
    sa.Column('password', sa.CHAR(length=128), nullable=False),
    sa.Column('password_last', sa.JSON(), nullable=False),
    sa.Column('business', sa.BOOLEAN(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.Uuid(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=64), nullable=False),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('amenity', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=False),
    sa.Column('like_vag_score', sa.FLOAT(), nullable=False),
    sa.Column('like_count', sa.INTEGER(), nullable=False),
    sa.Column('clip_count', sa.INTEGER(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('checkin', sa.DateTime(), nullable=False),
    sa.Column('checkout', sa.DateTime(), nullable=False),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('hashtag', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('public', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_id'), ['id'], unique=False)

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('nationality', sa.CHAR(length=2), nullable=False),
    sa.Column('like', sa.JSON(), nullable=False),
    sa.Column('accommodation', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('clip', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('follow', sa.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('comment', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profiles_id'), ['id'], unique=False)

    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('head_count', sa.INTEGER(), nullable=False),
    sa.Column('checkin', sa.DateTime(), nullable=False),
    sa.Column('checkout', sa.DateTime(), nullable=False),
    sa.Column('payment_price', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservations_id'), ['id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.Uuid(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('public', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_id'))

    op.drop_table('comments')
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservations_id'))

    op.drop_table('reservations')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_id'))

    op.drop_table('profiles')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_id'))

    op.drop_table('posts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('hashtags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hashtags_id'))

    op.drop_table('hashtags')
    # ### end Alembic commands ###
