"""post update2

Revision ID: f3ef46f67144
Revises: b2880a6a0ed7
Create Date: 2024-03-15 08:33:41.171862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3ef46f67144'
down_revision = 'b2880a6a0ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_start_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('available_end_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('checkout')
        batch_op.drop_column('checkin')
        batch_op.drop_column('start_at')
        batch_op.drop_column('end_at')

    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('check_out', sa.DateTime(), nullable=False))
        batch_op.drop_column('checkin')
        batch_op.drop_column('checkout')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('checkin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('check_out')
        batch_op.drop_column('check_in')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_at', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_at', postgresql.TIME(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('checkin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('checkout', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('available_end_at')
        batch_op.drop_column('available_start_at')

    # ### end Alembic commands ###
