# Generated by Django 5.0.3 on 2024-03-20 05:48

import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.UUID("b98abab3-8952-4d16-94b6-f38d315905d9"),
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("password_last", models.JSONField(default=dict)),
                ("business", models.BooleanField(default=False)),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 20, 5, 48, 27, 237657, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 20, 5, 48, 27, 237657, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.SlugField(default=None, max_length=30, null=True)),
                ("nationality", models.CharField(max_length=2)),
                ("like", models.JSONField(default=dict)),
                (
                    "accommodation",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=30),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "clip",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "follow",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.UUIDField(), default=list, size=None
                    ),
                ),
                (
                    "comment",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), default=list, size=None
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auths.users"
                    ),
                ),
            ],
        ),
    ]
