# Generated by Django 5.0.3 on 2024-03-22 05:20

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_users_created_at_alter_users_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 30, 803440, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6a328bfc-b7f5-4e5e-9cb6-c722c77d0bc0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 22, 5, 20, 30, 803440, tzinfo=datetime.timezone.utc)),
        ),
    ]
