# Generated by Django 5.0.3 on 2024-03-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=18)),
                ('tag', models.CharField(max_length=30)),
                ('note', models.CharField(default=None, max_length=100, null=True)),
            ],
        ),
    ]
